from .facultate import FacultateSerializer
from .specializare import SpecializareSerializer
from .rol import RolSerializer
from .stare import StareSerializer
from .user_profiles import UserProfilesSerializer
from .tip import TipSerializer
from .organizator import OrganizatorSerializer
from .categorie import CategorieSerializer
from .tip_participare import TipParticipareSerializer
from .locatie import LocatieSerializer
from .eveniment import EvenimentSerializer
from .sponsor import SponsorSerializer
from .sponsor_eveniment import SponsorEvenimentSerializer
from .inregistrare import InregistrareSerializer
