from django.urls import path

from .views import (
    HomeView,
    FacultyView,
    SpecializationView,
    RoleView,
    StatusView,
    UserView,
    RegisterView,
    LoginView,
    GoogleAuthView,
    UserProfileView,
    CompleteProfileView,
    OrganizerTypeView,
    OrganizerView,
    CategoryView,
    ParticipationTypeView,
    LocationView,
    EventView,
    UpcomingEventsView,
    ValidateEventView,
    CancelEventView,
    SponsorView,
    EventSponsorView,
    RegistrationView,
    RegisterToEventView,
    CancelRegistrationView,
    CheckInView,
    FeedbackView,
    AddFeedbackView,
    MaterialTypeView,
    EventMaterialView,
    EventMaterialsByEventView,
    UploadEventMaterialView,
    FavoriteEventView,
    AddFavoriteEventView,
    RemoveFavoriteEventView,
    NotificationTypeView,
    NotificationView,
    MyNotificationsView,
    UnreadNotificationsView,
    MarkNotificationAsReadView,
    ReportView,
    EmailTokenView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("faculties/", FacultyView.as_view(), name="faculty"),
    path("faculties/<int:pk>/", FacultyView.as_view(), name="faculty-detail"),
    path("specializations/", SpecializationView.as_view(), name="specialization"),
    path(
        "specializations/<int:pk>/",
        SpecializationView.as_view(),
        name="specialization-detail",
    ),
    path("roles/", RoleView.as_view(), name="role"),
    path("roles/<int:pk>/", RoleView.as_view(), name="role-detail"),
    path("statuses/", StatusView.as_view(), name="status"),
    path("statuses/<int:pk>/", StatusView.as_view(), name="status-detail"),
    path("users/", UserView.as_view(), name="user"),
    path("users/<int:pk>/", UserView.as_view(), name="user-detail"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("auth/google/", GoogleAuthView.as_view(), name="google-auth"),
    path("user-profiles/", UserProfileView.as_view(), name="user-profile"),
    path(
        "user-profiles/<int:pk>/", UserProfileView.as_view(), name="user-profile-detail"
    ),
    path("complete-profile/", CompleteProfileView.as_view(), name="complete-profile"),
    path("organizer-types/", OrganizerTypeView.as_view(), name="organizer-type"),
    path(
        "organizer-types/<int:pk>/",
        OrganizerTypeView.as_view(),
        name="organizer-type-detail",
    ),
    path("organizers/", OrganizerView.as_view(), name="organizer"),
    path("organizers/<int:pk>/", OrganizerView.as_view(), name="organizer-detail"),
    path("categories/", CategoryView.as_view(), name="category"),
    path("categories/<int:pk>/", CategoryView.as_view(), name="category-detail"),
    path(
        "participation-types/",
        ParticipationTypeView.as_view(),
        name="participation-type",
    ),
    path(
        "participation-types/<int:pk>/",
        ParticipationTypeView.as_view(),
        name="participation-type-detail",
    ),
    path("locations/", LocationView.as_view(), name="location"),
    path("locations/<int:pk>/", LocationView.as_view(), name="location-detail"),
    path("events/", EventView.as_view(), name="event"),
    path("events/<int:pk>/", EventView.as_view(), name="event-detail"),
    path("events/upcoming/", UpcomingEventsView.as_view(), name="event-upcoming"),
    path(
        "events/<int:pk>/validate/", ValidateEventView.as_view(), name="event-validate"
    ),
    path("events/<int:pk>/cancel/", CancelEventView.as_view(), name="event-cancel"),
    path("sponsors/", SponsorView.as_view(), name="sponsor"),
    path("sponsors/<int:pk>/", SponsorView.as_view(), name="sponsor-detail"),
    path("event-sponsors/", EventSponsorView.as_view(), name="event-sponsor"),
    path(
        "event-sponsors/<int:pk>/",
        EventSponsorView.as_view(),
        name="event-sponsor-detail",
    ),
    path("registrations/", RegistrationView.as_view(), name="registration"),
    path(
        "registrations/<int:pk>/",
        RegistrationView.as_view(),
        name="registration-detail",
    ),
    path(
        "events/<int:event_id>/register/",
        RegisterToEventView.as_view(),
        name="event-register",
    ),
    path(
        "events/<int:event_id>/cancel-registration/",
        CancelRegistrationView.as_view(),
        name="event-cancel-registration",
    ),
    path(
        "registrations/<int:registration_id>/check-in/",
        CheckInView.as_view(),
        name="registration-check-in",
    ),
    path("feedbacks/", FeedbackView.as_view(), name="feedback"),
    path("feedbacks/<int:pk>/", FeedbackView.as_view(), name="feedback-detail"),
    path(
        "events/<int:event_id>/feedback/",
        AddFeedbackView.as_view(),
        name="event-feedback",
    ),
    path("material-types/", MaterialTypeView.as_view(), name="material-type"),
    path(
        "material-types/<int:pk>/",
        MaterialTypeView.as_view(),
        name="material-type-detail",
    ),
    path("event-materials/", EventMaterialView.as_view(), name="event-material"),
    path(
        "event-materials/<int:pk>/",
        EventMaterialView.as_view(),
        name="event-material-detail",
    ),
    path(
        "events/<int:event_id>/materials/",
        EventMaterialsByEventView.as_view(),
        name="event-materials-by-event",
    ),
    path(
        "events/<int:event_id>/materials/upload/",
        UploadEventMaterialView.as_view(),
        name="event-material-upload",
    ),
    path("favorite-events/", FavoriteEventView.as_view(), name="favorite-event"),
    path(
        "favorite-events/<int:pk>/",
        FavoriteEventView.as_view(),
        name="favorite-event-detail",
    ),
    path(
        "events/<int:event_id>/favorite/",
        AddFavoriteEventView.as_view(),
        name="event-favorite-add",
    ),
    path(
        "events/<int:event_id>/favorite/remove/",
        RemoveFavoriteEventView.as_view(),
        name="event-favorite-remove",
    ),
    path(
        "notification-types/", NotificationTypeView.as_view(), name="notification-type"
    ),
    path(
        "notification-types/<int:pk>/",
        NotificationTypeView.as_view(),
        name="notification-type-detail",
    ),
    path("notifications/", NotificationView.as_view(), name="notification"),
    path(
        "notifications/<int:pk>/",
        NotificationView.as_view(),
        name="notification-detail",
    ),
    path("my-notifications/", MyNotificationsView.as_view(), name="my-notifications"),
    path(
        "my-notifications/unread/",
        UnreadNotificationsView.as_view(),
        name="unread-notifications",
    ),
    path(
        "notifications/<int:notification_id>/read/",
        MarkNotificationAsReadView.as_view(),
        name="notification-read",
    ),
    path("reports/", ReportView.as_view(), name="report"),
    path("reports/<int:pk>/", ReportView.as_view(), name="report-detail"),
    path("email-tokens/", EmailTokenView.as_view(), name="email-token"),
    path("email-tokens/<int:pk>/", EmailTokenView.as_view(), name="email-token-detail"),
]
