# Generated by Django 6.0.3 on 2026-06-02 09:00

import domain.models.event_material
import domain.models.registration
import domain.models.report
import domain.models.sponsor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaterial',
            name='file',
            field=models.FileField(upload_to=domain.models.event_material.event_material_upload_path),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ticket_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=domain.models.registration.registration_ticket_qr_upload_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=domain.models.report.report_upload_path),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=domain.models.sponsor.sponsor_logo_upload_path),
        ),
    ]
