from .base_repository import BaseRepository
from .category import CategoryRepository
from .status import StatusRepository
from .role import RoleRepository
from .faculty import FacultyRepository
from .specialization import SpecializationRepository
from .participation_type import ParticipationTypeRepository
from .location import LocationRepository
from .organizer_type import OrganizerTypeRepository
from .organizer import OrganizerRepository
from .event import EventRepository
from .registration import RegistrationRepository
from .feedback import FeedbackRepository
from .material_type import MaterialTypeRepository
from .event_material import EventMaterialRepository
from .sponsor import SponsorRepository
from .event_sponsor import EventSponsorRepository
from .favorite_event import FavoriteEventRepository
from .notification_type import NotificationTypeRepository
from .notification import NotificationRepository
from .report import ReportRepository
from .user_profile import UserProfileRepository
from .email_token import EmailTokenRepository
from .user import UserRepository
