from .default_data import (
    default_user_data,
    default_status_data,
    default_role_data,
    default_faculty_data,
    default_specialization_data,
    default_user_profile_data,
    default_organizer_type_data,
    default_organizer_data,
    default_category_data,
    default_participation_type_data,
    default_location_data,
    default_event_data,
    default_sponsor_data,
    default_event_sponsor_data,
    default_registration_data,
    default_feedback_data,
    default_material_type_data,
    default_event_material_data,
    default_favorite_event_data,
    default_notification_type_data,
    default_notification_data,
    default_report_data,
    default_email_token_data,
)

from .signals import insert_default_data
