from api.repository import StatusRepository


def default_sponsor_data():
    status_repository = StatusRepository()

    active_status = status_repository.get_instance_by_name("Activ")

    return [
        {
            "name": "ASSIST Software",
            "description": "Software company from Suceava involved in educational events, internships and workshops for students.",
            "link": "https://assist-software.net",
            "logo": "sponsors/logos/assist.png",
            "status": active_status,
        },
        {
            "name": "EGGER Romania",
            "description": "International wood processing company supporting engineering and environmental initiatives.",
            "link": "https://www.egger.com",
            "logo": "sponsors/logos/egger.png",
            "status": active_status,
        },
        {
            "name": "Bitdefender",
            "description": "Romanian cybersecurity company supporting IT education and security related events.",
            "link": "https://www.bitdefender.com",
            "logo": "sponsors/logos/bitdefender.png",
            "status": active_status,
        },
        {
            "name": "OSF Digital",
            "description": "Technology company involved in digital transformation and educational collaborations.",
            "link": "https://osf.digital",
            "logo": "sponsors/logos/osf_digital.png",
            "status": active_status,
        },
        {
            "name": "Silicon Service",
            "description": "IT company collaborating with technical faculties and student activities.",
            "link": "https://www.siliconservice.ro",
            "logo": "sponsors/logos/silicon_service.png",
            "status": active_status,
        },
        {
            "name": "Amazon",
            "description": "Global technology company supporting educational and software engineering initiatives.",
            "link": "https://www.amazon.com",
            "logo": "sponsors/logos/amazon.png",
            "status": active_status,
        },
        {
            "name": "Continental",
            "description": "Engineering and automotive technology company involved in student recruitment and workshops.",
            "link": "https://www.continental.com",
            "logo": "sponsors/logos/continental.png",
            "status": active_status,
        },
        {
            "name": "Bosch Romania",
            "description": "Technology and engineering company supporting innovation and technical education.",
            "link": "https://www.bosch.ro",
            "logo": "sponsors/logos/bosch.png",
            "status": active_status,
        },
        {
            "name": "Microsoft",
            "description": "Technology company supporting software development and cloud computing education.",
            "link": "https://www.microsoft.com",
            "logo": "sponsors/logos/microsoft.png",
            "status": active_status,
        },
        {
            "name": "Oracle",
            "description": "Enterprise software company involved in academic and database related initiatives.",
            "link": "https://www.oracle.com",
            "logo": "sponsors/logos/oracle.png",
            "status": active_status,
        },
        {
            "name": "IBM",
            "description": "Technology and research company supporting innovation and artificial intelligence events.",
            "link": "https://www.ibm.com",
            "logo": "sponsors/logos/ibm.png",
            "status": active_status,
        },
        {
            "name": "Endava",
            "description": "Software engineering company supporting student career development and IT events.",
            "link": "https://www.endava.com",
            "logo": "sponsors/logos/endava.png",
            "status": active_status,
        },
        {
            "name": "Stefanini",
            "description": "Global IT services company collaborating in technical and educational activities.",
            "link": "https://stefanini.com",
            "logo": "sponsors/logos/stefanini.png",
            "status": active_status,
        },
        {
            "name": "Pentalog",
            "description": "Software outsourcing company supporting technology conferences and recruitment events.",
            "link": "https://www.pentalog.com",
            "logo": "sponsors/logos/pentalog.png",
            "status": active_status,
        },
        {
            "name": "Atos",
            "description": "Digital transformation company involved in academic partnerships and student development.",
            "link": "https://atos.net",
            "logo": "sponsors/logos/atos.png",
            "status": active_status,
        },
        {
            "name": "Mambu",
            "description": "Fintech company supporting software engineering and innovation activities.",
            "link": "https://mambu.com",
            "logo": "sponsors/logos/mambu.png",
            "status": active_status,
        },
        {
            "name": "Arobs",
            "description": "Romanian software company supporting student competitions and educational events.",
            "link": "https://www.arobs.com",
            "logo": "sponsors/logos/arobs.png",
            "status": active_status,
        },
        {
            "name": "NTT DATA Romania",
            "description": "IT services company collaborating in educational and recruitment initiatives.",
            "link": "https://ro.nttdata.com",
            "logo": "sponsors/logos/ntt_data.png",
            "status": active_status,
        },
        {
            "name": "ING Hubs Romania",
            "description": "Technology and financial services company supporting innovation and career events.",
            "link": "https://inghubs.ro",
            "logo": "sponsors/logos/ing_hubs.png",
            "status": active_status,
        },
        {
            "name": "Orange Romania",
            "description": "Telecommunications company supporting networking and communication technologies education.",
            "link": "https://www.orange.ro",
            "logo": "sponsors/logos/orange.png",
            "status": active_status,
        },
        {
            "name": "Vodafone Romania",
            "description": "Telecommunications company involved in technology and connectivity initiatives.",
            "link": "https://www.vodafone.ro",
            "logo": "sponsors/logos/vodafone.png",
            "status": active_status,
        },
        {
            "name": "Dedeman",
            "description": "Romanian retail company supporting educational and community projects.",
            "link": "https://www.dedeman.ro",
            "logo": "sponsors/logos/dedeman.png",
            "status": active_status,
        },
        {
            "name": "BCR",
            "description": "Banking institution supporting entrepreneurship and financial education events.",
            "link": "https://www.bcr.ro",
            "logo": "sponsors/logos/bcr.png",
            "status": active_status,
        },
        {
            "name": "BRD",
            "description": "Bank supporting student development and educational activities.",
            "link": "https://www.brd.ro",
            "logo": "sponsors/logos/brd.png",
            "status": active_status,
        },
        {
            "name": "Raiffeisen Bank",
            "description": "Financial institution supporting career and entrepreneurship events.",
            "link": "https://www.raiffeisen.ro",
            "logo": "sponsors/logos/raiffeisen.png",
            "status": active_status,
        },
        {
            "name": "Coca-Cola HBC",
            "description": "International beverage company supporting social and student events.",
            "link": "https://ro.coca-colahellenic.com",
            "logo": "sponsors/logos/coca_cola.png",
            "status": active_status,
        },
        {
            "name": "Aqua Carpatica",
            "description": "Romanian brand supporting university and student community events.",
            "link": "https://aquacarpatica.com",
            "logo": "sponsors/logos/aqua_carpatica.png",
            "status": active_status,
        },
        {
            "name": "Radio USV",
            "description": "University media partner involved in promoting academic and student events.",
            "link": "https://radio.usv.ro",
            "logo": "sponsors/logos/radio_usv.png",
            "status": active_status,
        },
        {
            "name": "Monitorul de Suceava",
            "description": "Local media publication promoting educational and cultural events.",
            "link": "https://www.monitorulsv.ro",
            "logo": "sponsors/logos/monitorul_suceava.png",
            "status": active_status,
        },
        {
            "name": "Intermedia TV",
            "description": "Regional television partner involved in promoting university initiatives.",
            "link": "https://www.intermediatv.ro",
            "logo": "sponsors/logos/intermedia_tv.png",
            "status": active_status,
        },
        {
            "name": "Primaria Municipiului Suceava",
            "description": "Public institution supporting educational, cultural and community initiatives.",
            "link": "https://www.primariasv.ro",
            "logo": "sponsors/logos/primaria_suceava.png",
            "status": active_status,
        },
        {
            "name": "Consiliul Judetean Suceava",
            "description": "County administration institution supporting regional academic and cultural projects.",
            "link": "https://www.cjsuceava.ro",
            "logo": "sponsors/logos/cj_suceava.png",
            "status": active_status,
        },
        {
            "name": "Camera de Comert si Industrie Suceava",
            "description": "Business institution supporting entrepreneurship and professional development activities.",
            "link": "https://ccisv.ro",
            "logo": "sponsors/logos/cci_suceava.png",
            "status": active_status,
        },
        {
            "name": "USV",
            "description": "Universitatea Stefan cel Mare din Suceava supporting academic and student events.",
            "link": "https://www.usv.ro",
            "logo": "sponsors/logos/usv.png",
            "status": active_status,
        },
    ]
