def default_user_data():
    return [
        # ==========================================
        # DEFAULT SYSTEM USERS
        # ==========================================
        {
            "username": "administrator",
            "password": "Admin#1",
            "email": "admin@usv.ro",
            "first_name": "System",
            "last_name": "Administrator",
            "is_staff": True,
            "is_superuser": True,
        },
        {
            "username": "student",
            "password": "Student#1",
            "email": "student@student.usv.ro",
            "first_name": "Default",
            "last_name": "Student",
        },
        {
            "username": "professor",
            "password": "Professor#1",
            "email": "professor@usv.ro",
            "first_name": "Default",
            "last_name": "Professor",
        },
        {
            "username": "partner",
            "password": "Partner#1",
            "email": "partner@example.com",
            "first_name": "Default",
            "last_name": "Partner",
        },
        {
            "username": "organization",
            "password": "Organization#1",
            "email": "organization@example.com",
            "first_name": "Default",
            "last_name": "Organization",
        },
        {
            "username": "guest",
            "password": "Guest#1",
            "email": "guest@example.com",
            "first_name": "Default",
            "last_name": "Guest",
        },
        # ==========================================
        # ORGANIZER USERS
        # ==========================================
        {
            "username": "organization_firesc",
            "password": "Organization#1",
            "email": "firesc@usv.ro",
            "first_name": "FIRESC",
            "last_name": "Organization",
        },
        {
            "username": "organization_asus",
            "password": "Organization#1",
            "email": "asus@usv.ro",
            "first_name": "ASUS",
            "last_name": "Organization",
        },
        {
            "username": "organization_aiesec",
            "password": "Organization#1",
            "email": "aiesec@usv.ro",
            "first_name": "AIESEC",
            "last_name": "Organization",
        },
        {
            "username": "organization_anssa",
            "password": "Organization#1",
            "email": "anssa@usv.ro",
            "first_name": "ANSSA",
            "last_name": "Organization",
        },
        {
            "username": "organization_ascor",
            "password": "Organization#1",
            "email": "ascor@usv.ro",
            "first_name": "ASCOR",
            "last_name": "Organization",
        },
        {
            "username": "organization_arcanul",
            "password": "Organization#1",
            "email": "arcanul@usv.ro",
            "first_name": "Arcanul",
            "last_name": "Organization",
        },
        {
            "username": "organization_tonitza",
            "password": "Organization#1",
            "email": "tonitza@usv.ro",
            "first_name": "Tonitza",
            "last_name": "Organization",
        },
        {
            "username": "organization_fabulinus",
            "password": "Organization#1",
            "email": "fabulinus@usv.ro",
            "first_name": "Fabulinus",
            "last_name": "Organization",
        },
        {
            "username": "organization_ccs_usv",
            "password": "Organization#1",
            "email": "ccs@usv.ro",
            "first_name": "CCS",
            "last_name": "USV",
        },
        {
            "username": "organization_biblioteca_usv",
            "password": "Organization#1",
            "email": "biblioteca@usv.ro",
            "first_name": "Biblioteca",
            "last_name": "USV",
        },
        {
            "username": "organization_ccoc_usv",
            "password": "Organization#1",
            "email": "ccoc@usv.ro",
            "first_name": "CCOC",
            "last_name": "USV",
        },
        {
            "username": "organization_radio_usv",
            "password": "Organization#1",
            "email": "radio@usv.ro",
            "first_name": "Radio",
            "last_name": "USV",
        },
        {
            "username": "organization_dep_calculatoare",
            "password": "Organization#1",
            "email": "calculatoare@usv.ro",
            "first_name": "Departamentul",
            "last_name": "Calculatoare",
        },
        {
            "username": "organization_dep_electrotehnica",
            "password": "Organization#1",
            "email": "electrotehnica@usv.ro",
            "first_name": "Departamentul",
            "last_name": "Electrotehnica",
        },
        {
            "username": "organization_fiesc",
            "password": "Organization#1",
            "email": "fiesc@usv.ro",
            "first_name": "FIESC",
            "last_name": "USV",
        },
        {
            "username": "organization_feea",
            "password": "Organization#1",
            "email": "feaa@usv.ro",
            "first_name": "FEAA",
            "last_name": "USV",
        },
        {
            "username": "organization_fdsa",
            "password": "Organization#1",
            "email": "fdsa@usv.ro",
            "first_name": "FDSA",
            "last_name": "USV",
        },
        {
            "username": "organization_flsc",
            "password": "Organization#1",
            "email": "flsc@usv.ro",
            "first_name": "FLSC",
            "last_name": "USV",
        },
        {
            "username": "organization_fpse",
            "password": "Organization#1",
            "email": "fpse@usv.ro",
            "first_name": "FPSE",
            "last_name": "USV",
        },
        {
            "username": "organization_silvicultura",
            "password": "Organization#1",
            "email": "silvicultura@usv.ro",
            "first_name": "Silvicultura",
            "last_name": "USV",
        },
        {
            "username": "organization_fia",
            "password": "Organization#1",
            "email": "fia@usv.ro",
            "first_name": "FIA",
            "last_name": "USV",
        },
        {
            "username": "organization_fimar",
            "password": "Organization#1",
            "email": "fimar@usv.ro",
            "first_name": "FIMAR",
            "last_name": "USV",
        },
        {
            "username": "organization_fefs",
            "password": "Organization#1",
            "email": "fefs@usv.ro",
            "first_name": "FEFS",
            "last_name": "USV",
        },
        {
            "username": "organization_figs",
            "password": "Organization#1",
            "email": "figs@usv.ro",
            "first_name": "FIGS",
            "last_name": "USV",
        },
        {
            "username": "organization_fmsb",
            "password": "Organization#1",
            "email": "fmsb@usv.ro",
            "first_name": "FMSB",
            "last_name": "USV",
        },
        {
            "username": "organization_assist",
            "password": "Organization#1",
            "email": "assist@assist-software.net",
            "first_name": "ASSIST",
            "last_name": "Software",
        },
        {
            "username": "organization_osf",
            "password": "Organization#1",
            "email": "contact@osf.digital",
            "first_name": "OSF",
            "last_name": "Digital",
        },
        {
            "username": "organization_silicon_service",
            "password": "Organization#1",
            "email": "contact@siliconservice.ro",
            "first_name": "Silicon",
            "last_name": "Service",
        },
        {
            "username": "organization_volter",
            "password": "Organization#1",
            "email": "office@volter.ro",
            "first_name": "Volter",
            "last_name": "Romania",
        },
        {
            "username": "organization_ca_connect",
            "password": "Organization#1",
            "email": "contact@caconnect.ro",
            "first_name": "CA",
            "last_name": "Connect",
        },
        {
            "username": "organization_schuman",
            "password": "Organization#1",
            "email": "contact@schuman.ro",
            "first_name": "Fundatia",
            "last_name": "Schuman",
        },
        {
            "username": "organization_cj_suceava",
            "password": "Organization#1",
            "email": "contact@cjsuceava.ro",
            "first_name": "Consiliul",
            "last_name": "Judetean",
        },
        {
            "username": "organization_primaria_suceava",
            "password": "Organization#1",
            "email": "primaria@primariasv.ro",
            "first_name": "Primaria",
            "last_name": "Suceava",
        },
        {
            "username": "organization_teatrul_vasilache",
            "password": "Organization#1",
            "email": "contact@teatrulvasilache.ro",
            "first_name": "Teatrul",
            "last_name": "Vasilache",
        },
        {
            "username": "organization_evoluat",
            "password": "Organization#1",
            "email": "contact@evoluat.ro",
            "first_name": "Evoluat",
            "last_name": "Agency",
        },
    ]
